name: CI
on:
  push:
  pull_request:
  release:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test units
        run: |
          npm ci
          npm test
        env:
          CODECOV_TOKEN: "59b05691e2ef9a29f56fb98645966f0d453164b1"
          CI: true

  build:
    if: github.ref == 'refs/heads/master' || github.event_name == 'release'
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build . --tag nicopetitot/nicolaspetitot-vps:master
      - name: Push Docker image to the Docker Hub
        run: |
          docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
          docker push nicopetitot/nicolaspetitot-vps:master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  release:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15]

    steps:
      - name: Add the release tag
        run: |
          docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
          docker pull nicopetitot/nicolaspetitot-vps:master
          docker tag nicopetitot/nicolaspetitot-vps:master nicopetitot/nicolaspetitot-vps:$VERSION
          docker push nicopetitot/nicolaspetitot-vps:$VERSION
          docker tag nicopetitot/nicolaspetitot-vps:master nicopetitot/nicolaspetitot-vps:latest
          docker push nicopetitot/nicolaspetitot-vps:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: ${{ github.event.release.tag_name }}
